jobs:
- job:
  displayName: Run Python Script on Ubuntu
  pool:
    vmImage: ubuntu-latest
  strategy:
    matrix:
      Python36:
        python.version: '3.6'

  steps:
  - bash: python run.py
    displayName: Run Script