version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  run-python-script:
    executor: python/default
    steps:
      - checkout
      - run:
          name: Run Script
          command: python run.py

workflows:
  main:
    jobs:
      - run-python-script
