name: Run Python script on Windows
on:
  push:
    branches:
      - master

jobs:
  run-python-script:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build Image
        run: docker build -t stephenroille/benchmark .
        shell: bash
      - name: Run Script from Container
        run: docker run --rm stephenroille/benchmark
        shell: bash
